
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TaskServiceImplService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8888/TaskService?wsdl")
public class TaskServiceImplService
    extends Service
{

    private final static URL TASKSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TASKSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TASKSERVICEIMPLSERVICE_QNAME = new QName("http://service/", "TaskServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/TaskService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TASKSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TASKSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TaskServiceImplService() {
        super(__getWsdlLocation(), TASKSERVICEIMPLSERVICE_QNAME);
    }

    public TaskServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TASKSERVICEIMPLSERVICE_QNAME, features);
    }

    public TaskServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TASKSERVICEIMPLSERVICE_QNAME);
    }

    public TaskServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TASKSERVICEIMPLSERVICE_QNAME, features);
    }

    public TaskServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaskServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TaskService
     */
    @WebEndpoint(name = "TaskServiceImplPort")
    public TaskService getTaskServiceImplPort() {
        return super.getPort(new QName("http://service/", "TaskServiceImplPort"), TaskService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaskService
     */
    @WebEndpoint(name = "TaskServiceImplPort")
    public TaskService getTaskServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "TaskServiceImplPort"), TaskService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TASKSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TASKSERVICEIMPLSERVICE_EXCEPTION;
        }
        return TASKSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
